sources:
  - source_id: sales_orders

    source_system: sales

    source_type: file

    load_type: streaming

    enabled: true

    priority: 100

    primary_keys:
      - order_id

    watermark_column: modified_at

    file_format: json

    reader_options:
      cloudFiles.schemaLocation: /Volumes/workspace/landing/source_files/_schemas/orders
      cloudFiles.schemaEvolutionMode: addNewColumns
      cloudFiles.inferColumnTypes: true
      cloudFiles.includeExistingFiles: true
      rescuedDataColumn: _rescued_data

    location:
      object_name: orders
      path: /Volumes/workspace/landing/source_files/orders

    target:
      catalog_name: workspace
      bronze_schema: bronze
      silver_schema: silver
      gold_schema: gold
      quarantine_schema: quarantine

      bronze_table: bronze_orders
      silver_table: silver_orders

      checkpoint_path: /Volumes/workspace/landing/source_files/_checkpoints/orders
      schema_location_path: /Volumes/workspace/landing/source_files/_schemas/orders

    standardization:
      columns:
        - source_column: order_id
          data_type: long

        - source_column: customer_id
          data_type: long

        - source_column: order_total
          data_type: decimal(18,2)

        - source_column: modified_at
          data_type: timestamp

        - source_column: order_status
          data_type: string
          trim: true
          text_case: lower


    governance:
      business_domain: sales
      owner: data-platform
